#!/bin/sh

LIST="auszvuvh001 auszvuvh002 auszvuvh003 auszvuvh004 auszvuvh005 auszvuvh006"

for i in $LIST
do
	if [ _"$1" = _-get ]
	then
		if [ _"$2" = _ ] ; then echo "get what?" ; exit 1 ; fi
		F=`echo "$i" | sed "s/.*\(.\)/\1/"`
		CMD="scp fz6v7m@$i:$2 $F"
	elif [ _"$1" = _-put ]
	then
		if [ _"$2" = _ ] ; then echo "put what?" ; exit 1 ; fi
		if [ _"$3" = _ ] ; then F="$2" ; else F="$3" ; fi
		CMD="scp $2 fz6v7m@$i:$F"
	else
		CMD="ssh fz6v7m@$i $@"
	fi
	echo ""
	echo "$CMD"
	$CMD
done
