#!/usr/local/bin/bash
# get today's date
SEARCH_FILENAME=`echo "$QUERY_STRING" | sed -n 's/^.*Filename=\([^&]*\).*$/\1/p' | sed "s/%20/ /g"`
SEARCH_CONTENT=`echo "$QUERY_STRING" | sed -n 's/^.*Content=\([^&]*\).*$/\1/p' | sed "s/%20/ /g"`
OUTPUT="$(date)"

. variables

SCRIPTBASE="/var/www/docunix/bin/scripts"
#VAR1=`$SCRIPTBASE/master.sh`
# You must add following two lines before
# outputting data to the web browser from shell
# script
echo "Content-type: text/html"
echo ""

cat << EOF1
<html><head><title>JD's Docunix Summary and Search Page</title></head><body>
<table border=1><tr><td colspan=2><a href="http://16.176.23.32/docunix" target=_parent > Docunix Home </a>
		|<a href="http://16.176.23.32/bin/search"> Pre-Canned Search Page </a>
		|<a href="http://16.176.23.32/bin/scripts/001-search"> Refresh this page </a></td></tr>
<tr><td colspan=2>
<form id='sampleform' method='get' action='/bin/scripts/001-search' >
   Search Filename: <input type='text' name='Filename' value='$SEARCH_FILENAME' />
   Content: <input type='text' name='Content' value='$SEARCH_CONTENT' />
   <input type='submit' name='Submit' value='Submit' />
   </p>
</form>
Notes:
<ul>
 <li>Searches are currently CaSe SeNsItIvE <br>
 <li>single words (no spaces) [ for now ] <br>
</ul>
Current Filename String =  $SEARCH_FILENAME <br>
Current Content String =  $SEARCH_CONTENT <br>
Current Search Base = $BASE
</td></tr>
EOF1


	# filename AND content given
	if [[ $SEARCH_CONTENT && $SEARCH_FILENAME ]]
	 then
		echo "<tr><td colspan=2 >Searching filenames THEN content:</td></tr>"
		for i in `find -L $BASE | grep $SEARCH_FILENAME`
		 do
			HOSTID=`echo $i | sed -n 's/^.*explorer.\([^.]*\).*$/\1/p'`
			NAME=`echo $i | awk -F. '{print $3}' | awk -F"-" '{print $1}'`
			FILENAME=`echo $i |  awk -F/ '{print substr($0, index($0,$6)) }'`
			NAME2=`echo $i |  awk -F/ '{print $4}'`
			COLLECTION=`echo $i |  awk -F/ '{print $5}'`
			PATH2=`echo $i | awk -F/ '{print substr($0, index($0,$6)) }' | sed -e 's/\//%2F/'`
cat << EOF2
			<tr><td>$NAME, $HOSTID<br>
			File = <a href="http://16.176.23.32/bin/fileview?name=${NAME2}&collection=${COLLECTION}&path=${PATH2}" target=_blank>
				$FILENAME</a>
			</td><td>
			<pre>
EOF2

			grep $SEARCH_CONTENT $i
			FILENAME_COUNT=$(( $FILENAME_COUNT + 1 ))
		done
	
cat << EOF3
		</pre>
		</td></tr>
		<tr><td><br>... done ($FILENAME_COUNT files)
		</td></tr>
EOF3

	# filename only 
	elif [[ -z $SEARCH_CONTENT  && $SEARCH_FILENAME ]]
	 then
		echo "<tr><td>"
		echo "Searching filenames:<br>"
		echo "</tr></td>"
		FILENAME_COUNT=`find -L $BASE | grep $SEARCH_FILENAME | wc -l`
		for i in `find -L $BASE | grep $SEARCH_FILENAME`
		 do	
			HOSTID=`echo $i | sed -n 's/^.*explorer.\([^.]*\).*$/\1/p'`
			NAME=`echo $i | awk -F. '{print $3}' | awk -F"-" '{print $1}'`
			FILENAME=`echo $i |  awk -F/ '{print substr($0, index($0,$6)) }'`
			NAME2=`echo $i |  awk -F/ '{print $4}'`
			COLLECTION=`echo $i |  awk -F/ '{print $5}'`
			PATH2=`echo $i | awk -F/ '{print substr($0, index($0,$6)) }' | sed -e 's/\//%2F/'`
cat << EOF21		
			<tr><td>
			$NAME, $HOSTID<br>
			File = <a href="http://16.176.23.32/bin/fileview?name=${NAME2}&collection=${COLLECTION}&path=${PATH2}" target=_blank>
				$FILENAME</a>
			<td><pre>
			$i
			</pre></td></tr>
EOF21
		done
		echo "<tr><td>"
		echo "<br>... done ($FILENAME_COUNT files)"
		echo "</td></tr>"

	# content only 
	elif [[ $SEARCH_CONTENT && -z $SEARCH_FILENAME ]]
	 then
		echo "<tr><td>"
		echo "Searching all file contents:<br>"
		for i in `find -L $BASE`
		 do
			grep "$SEARCH_CONTENT" $i > /dev/null 2>&1 
			if [ $? -eq "0" ] ; then 
				echo "<tr><td>File: $i </td><td><pre>" 
				grep "$SEARCH_CONTENT" $i 
				echo "</pre>"
				FILENAME_COUNT=$(( $FILENAME_COUNT + 1 ))
			fi
		done
		echo "<br>... done ($FILENAME_COUNT files)"
		echo "</td></tr>"
			

	else
		echo "<tr><td>No Input Received!"
		echo "<br>... done</td></tr>"
	fi 

cat << EOF4
</table>

</tr></table>
<hr>Today is $OUTPUT <br>
Current directory is $(pwd) <br>
Shell Script name is $0
</body></html>
EOF4
