#!/bin/bash
#
# create a list of http: links for sharepoint files
#
## VAR
DATE2=`date +%Y-%m-%d-%H%M%S`
DEST="/Volumes/apj_ito_transformation_dct/msf/Shared Documents/APJ DCT UNIX/LST-FILE-LINKS"
VAR1="http://ent212.sharepoint.hp.com/teams/apj_ito_transformation_dct/sp_dcc/Burwood%20%20Sysmc/EDS%20Leveraged%20-%20Leveraged%20Services%20and%20Tools"
VAR2="/Volumes/apj_ito_transformation_dct/sp_dcc/Burwood  Sysmc/EDS Leveraged - Leveraged Services and Tools"
FILE1="lst.file.links.JD.list"
FILE2="lst.file.links.JD.html"
line1=
line2=

FOLDER1="Deliverables"
FOLDER2="LST CMO Discovery"
FOLDER3="Technical Forum Working Folder/UVH"



# FUNCTIONS
#

loopme(){

[ ! -d "$VAR2/$1" ] 	&& echo "$VAR2/$1 missing...exiting. ($VAR2/$1)" \
			&& exit 1 \
			|| echo "search folder = ok ($VAR2/$1)"
cd "$VAR2/$1"
PWD1=`pwd | sed -e "s/\/\$//" -e "s/.*\///"`		# get last field (or folder name)
PWD2=`pwd | sed "s/\(.*\)\/.*/\1/"`			# get everything EXCEPT last field (or folder name)

#echo "loop: $1 || pwd1: $PWD1 || pwd2: $PWD2 || file: $FILE1"

# find all files, and write to temp file1
cd "$VAR2"
find "$1" | sort >> "/tmp/$FILE1"

# create the html in a second file 
cat "/tmp/$FILE1" | while read line 

 do
#	echo "$count. Line=$line"
	line2=`echo $line | sed "s/\(.*\)\/.*/\1/"`
	line3=`echo $line | sed -e "s/\/\$//" -e "s/.*\///"`
#	echo "$count. Parent=$line2"
	if [ "$line2old" = "$line2" ] 
	 then
		echo "<tr><td></td><td><a href=\"$VAR1/$line\">$line3</a><br></td></tr>" $'\r' >> "/tmp/$FILE2"
	 else
		echo "<tr><td><a href=\"$VAR1/$line2\">$line2</a></td><td><a href=\"$VAR1/$line\">$line3</a><br></td></tr>" $'\r' >> "/tmp/$FILE2"
	fi
	line2old=$line2
done

}

# SCRIPT ###################

[ -f "$DEST/$FILE2" ] 	&& echo ".. moving old file to archive/$DATE2.$FILE2" \
			&& mv "$DEST/$FILE2" "$DEST/archive/$DATE2.$FILE2"

[ -f "/tmp/$FILE1" ] && rm "/tmp/$FILE1"

[ ! -d "$DEST" ] 	&& echo "file links folder missing...exiting. ($DEST)" \
			&& exit 1 \
			|| echo "file links folder = ok ($DEST)"
[ ! -d "$VAR2" ] 	&& echo "search base folder missing...exiting. ($VAR2)" \
			&& exit 1 \
			|| echo "search base folder = ok ($VAR2)"

echo "---- generated by file-links.sh on $DATE2 ----" > /tmp/$FILE2
echo "<table border=1><tr><td>Parent</td><td>File</td></tr>" >> /tmp/$FILE2

count=1
loopme "$FOLDER1" 
count=2
loopme "$FOLDER2"
count=3
loopme "$FOLDER3"
wait

echo "</table>" >> /tmp/$FILE2
echo "... copying /tmp/$FILE2 to $DEST"
cp "/tmp/$FILE2" "$DEST/$FILE2"

#
# The End !
